- name: Install autofs
  become: true
  ansible.builtin.dnf:
    name: autofs
    state: present

- name: Ensure autofs directories exist
  ansible.builtin.file:
    path: "{{ nfs_autofs_local.auto_master_path }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ nfs_autofs_local.entries }}"
  become: true

- name: Copy auto.master config
  become: true
  ansible.builtin.template:
    src: "templates/auto.master.j2"
    dest: /etc/auto.master
    mode: "0640"

- name: Copy auto.nfs config
  become: true
  ansible.builtin.template:
    src: "templates/auto.nfs.j2"
    dest: /etc/auto.nfs
    mode: "0640"

- name: Restart autofs
  become: true
  ansible.builtin.systemd:
    name: autofs
    state: restarted
    masked: false
    enabled: true
