- name: Extract Worker Token and IP (Only after Swarm Initialization)
  ansible.builtin.set_fact:
    worker_token: "{{ hostvars[groups['swarm_managers'][0]].worker_token }}"
    swarm_manager_ip: "{{ hostvars[groups['swarm_managers'][0]].swarm_manager_ip }}"
  run_once: true
  when: worker_token is not defined

- name: Join the swarm as a worker (if not already in the cluster)
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ worker_token }}"
    remote_addrs:
      - "{{ swarm_manager_ip }}"
  when: worker_token is defined
