- name: Install required packages
  ansible.builtin.dnf:
    name:
      - python3-pip
      - dnf-plugins-core
      - ca-certificates
      - curl
      - gnupg2
    state: present
    update_cache: true

- name: Install docker python module
  ansible.builtin.pip:
    name:
      - docker

- name: Add Docker repo using dnf config-manager
  ansible.builtin.command:
    cmd: >
      dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker Engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ swarm_common_docker_user }}"
    groups: docker
    append: true

- name: Start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Permit traffic in default zone for swarm
  ansible.posix.firewalld:
    service: docker-swarm
    state: enabled
    permanent: true
    immediate: true